theme: minima
title: The GitHub Blog
author: Shubham Srivastava
email: shubhamsrivastava6059@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for getting started with GitHub pages, by working with
  a demo blog site creation.

# social links
twitter_username: Shubham6059 # DO NOT include the @ character, or else the build will fail!
github_username:  Shubham6059 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
